### ISSUE TITLE
Dynamically generate Actions build matrix

### ISSUE THREAD

**Issue by jovanbulck** [sancus-tee/sancus-examples#18]
We now hard code the sancus-examples test directories:

```
      matrix:
        example: [hello-world, sensor-reader, arithmetic, fileio, timer, violation, sancus-step, dma, dynamic-loader]
```

This can better be auto-generated using an `ls` in a first stage that is passed with a needs.output construct

https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/

**Comment by fritzalder** [comment]
Watch out, once we add the confidential loading example it will only work on a part of the matric (not aion). Not sure how to do this best.

**Comment by jovanbulck** [comment]
yes good point, but that's the neat thing about a GH Actions matrix, you can manually override some entries with `include`, eg I now already did that for the archive hello:

```
 	        include:
          - example: hello-library
            flags: ARCHIVE_MODE=thick 
            sancus-security: 64
          - example: hello-library
            flags: ARCHIVE_MODE=thin
            sancus-security: 64
```

basically, for Aion, we'll add another matrix expansion `core = [aion,sancus]` or so and then image becomes:

```
      image: docker.pkg.github.com/sancus-tee/sancus-main/${{matrix.core}}-devel-${{ matrix.sancus-security }}:latest
```

and everything beautifully auto-expands (explodes) to run on aion/sancus-devel-64/128 with possible exceptions indicated via include :tada: :grin:
